# values.yaml
# Global Settings
namespace: default
fullnameOverride: ""

# Elalert Application Configuration
app:
  name: "elalert"
  image: "briankeny/elalert:latest"
  pullPolicy: Always
  imagePullSecrets: ""
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: "default"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

rules:
  # External ConfigMap
  configMapName: "elalert-rules"
  # Mount path for rules
  mountPath: "/app/rules"

service:
  type: ClusterIP
  clusterIP: None  # Headless service

deployment:
  replicas: 1

secrets:
  env:
   elastic_api_key: ''
   elastic_url: 'https://elastic.example.com'
   es_index: '.alerts-*'
   webhook_url: ''
   app_log_file: 'Elalert.log'
   alerts_save_file: 'elalert.json'
   save: 'true'
   rules_folder: 'rules'
   interval: '30'
   timeframe: '30'
   verbose: 'false'
   pytz_timezone: 'Africa/Nairobi'
   hits_size: '1000'
   cleanup_schedule: '12:00,23:00'
   max_alerts_per_batch: '5'
   ignored_alert_keywords:  ''
   storage_type: 'sqlite'
