apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | default .Release.Name }}-svc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: {{ .Values.app.name | default .Release.Name}}
  clusterIP: None  