apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name | default .Values.app.name }}-pvc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  accessModes:
    - {{ .Values.app.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}