apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | default .Values.app.name  }}-secrets
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.app.name | default .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}